name = "PredicateComposition"
uuid = "ade9fadb-e73f-4130-b8d8-88ea9f6db656"
authors = ["Johannes Feist <johannes.feist@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
